- src/components/common/Input.tsx
- src/pages/index.tsx
- props로 placeholder받습니다.
자유롭게 해주세용
> [FE-4] 공통 컴포넌트 - Input 구현

- src/components/common/Top20List.tsx
- src/pages/index.tsx
- tailwind.config.js
- props 3개를 넘겨 줍니다 : ranking, title, count
자유롭게 해주세용
> [FE-7] 공통 컴포넌트 - Top20List 구현

- src/components/common/ProgressBar.tsx
- src/pages/index.tsx
정적 할당이 안되어서 style속성으로 넣어주었습니다.
https://velog.io/@arthur/Tailwind-CSS-%EC%97%90%EC%84%9C-%EB%8F%99%EC%A0%81%EC%9C%BC%EB%A1%9C-%ED%81%B4%EB%9E%98%EC%8A%A4-%ED%95%A0%EB%8B%B9%ED%95%98%EA%B8%B0
위 사이트 참고해서 해보려고 했는데, 안되네요 .. 그래서 style방식으로 동적 할당해주었습니다
> ProgressBar 스타일 수정

- src/components/common/Button.tsx
-property 옵션으로 어떤 버튼인지 설정 가능해요.
-type으로 버튼의 타입지정 가능해요
-children으로 만들었기에 일반 버튼태그처럼 쓰시면됩니당
자유롭게 리뷰남겨주세요
> feat: 버튼 컴포넌트 생성

- src/pages/browsing.tsx
- src/pages/index.tsx
-슬라이더 레이아웃 구현
-둘러보기 클릭시 라우팅
드래긓그해서 미는게 모바일에서 대처가 빡세서 기본로직으로 구현이 너무 빡세네요 ... 일단 시간 많이걸릴거같아서 그부분 제외하고 올릴게요
> feat: 메인 페이지 구현

- next.config.js
- src/pages/api/getUserQuestion.ts
- src/pages/question.tsx
- src/types/getUserQuestion.ts
-관련 next config수정
-질문 레이아웃
-topbar 백버튼은 리팩토링 이후 반영예정
-질문 다 클릭시 recommendation으로 동적라우팅
자유롭게 남겨주세용~~
> feat: 질문 페이지 구현

- src/pages/index.tsx
-오늘까지 구현 힘들거같아서 임시적으로 클릭시 넘어가도록 구현했습니다.
> fix: 슬라이더 클릭시 페이지 이동하도록

- src/styles/globals.css
> 반응형 웹 - global css 수정

- src/pages/begin.tsx
begin페이지 라우팅 추가하였습니다.
자유롭게 해주세용
> begin페이지 라우팅 추가

- src/pages/question.tsx
- src/types/getUserQuestion.ts
-staleTime infinite로 수정
-데이터값을 상태로 들고있도록 수정
https://user-images.githubusercontent.com/103626175/222139883-a13cd609-df9d-4361-b9ab-b8a2d3b62460.mov
자유롭게 리뷰 부탁용~
> fix: question페이지 버그 해결

- src/pages/_app.tsx
- src/pages/loading.tsx
- src/pages/question.tsx
- src/store/atom.ts
-질문 선택 완료시 로딩 페이지로이동
-로딩 페이지에서 사진 다 로딩되면 결과페이지로 이동
자유롭게 주세요
> feat:질문 완료시 로딩페이지로 이동

- src/components/common/Button.tsx
- src/pages/begin.tsx
단위 변경 및 nickname저장
- 리코일로 하면 새로고침했을 때 데이터가 날라가기도 하고, 굳이 쓸필요 없을 거 같아서 nickname은 loalStorage에 저장하였습니당
자유롭게 해주세용
> 단위 변경 및 nickname저장

- src/pages/index.tsx
-잠금해제 범위 안벗어나도록 max범위 설정
https://user-images.githubusercontent.com/103626175/222326831-959fd78b-0f29-46d0-9427-739e10507f0a.mov
> fix: 잠금해제 범위 안벗어나도록

- src/api/getUserQuestion.ts
- src/pages/begin.tsx
- src/pages/question.tsx
- src/styles/globals.css
-결과물 유저가 입력한 닉네임으로 받기
-begin페이지 라우팅 에러 해결
- 반응형 수정
> feat: 로딩창 닉네임 적용 반응형 리팩토링

- src/pages/question.tsx
> fix: 문제 12번에서 클릭시 13번 보임

- src/api/getUserCount.ts
- src/pages/index.tsx
- src/types/getUserCount.ts
> fix: 메인페이지 오타 수정 데이터 반영

- src/components/common/Button.tsx
- src/components/common/TopBar.tsx
- src/components/common/layout.tsx
- src/pages/begin.tsx
- src/pages/index.tsx
- src/pages/question.tsx
-스타일에 맞게 수정
- 반응형 수정
-begin페이지 버튼크기 수정
> feat: QA 리팩토링

- src/components/common/Button.tsx
- src/components/result/Card.tsx
- src/components/result/FitHobby.tsx
- src/components/result/KakaoShare.tsx
- src/components/result/Share.tsx
- src/pages/result.tsx
NextJS의 router를 이용하여 페이지를 분리하였습니다.
결과 페이지 : `/result?id=93`
홀랑 유형 페이지 : `/result?id=93&view=fitHobby`
공유하기 페이지 : `/result?id=93&view=share`
입니다
자유롭게 해주세용 ~~
> QA - 결과 페이지 분리

- src/components/common/Top20List.tsx
- src/components/common/layout.tsx
- src/pages/browsing.tsx
-관련 스타일 수정
-레이아웃 재설정
https://user-images.githubusercontent.com/103626175/222922968-6a411313-7d5b-490f-bbed-25e0028c4907.mov
자유롭게 주세용~
> refactor: 둘러보기 페이지 리팩토링

- src/components/common/layout.tsx
- src/pages/begin.tsx
-layout 폰화면에 맞게 수정
-begin버튼 위치 수정
자유롭게 주세용~
> feat: layout style, begin페이지 스타일 수정

- src/components/common/Button.tsx
- src/components/result/FitHobby.tsx
- src/components/result/HobbyDetail.tsx
- src/pages/_app.tsx
- src/pages/begin.tsx
- src/pages/question.tsx
- src/pages/result.tsx
1. 닉네임 입력 페이지 버튼 구현 (type=submit)
2. 질문 페이지 10 이하 0 제거
3. 경계선 추가
4. 결과 페이지 디자인 수정 반영
5. 컴포넌트 미리 띄우고 hidden으로 감춤 처리
자유롭게 해주세용 ~
> QA 수정사항 반영

- src/pages/begin.tsx
- src/pages/browsing.tsx
- src/pages/question.tsx
- src/pages/result.tsx
> fix: 뒤로가기 정책 반영

- src/pages/question.tsx
> fix: 로딩중 컴포넌트로 변경

- src/components/common/Button.tsx
- src/components/result/HobbyDetail.tsx
- src/components/result/Share.tsx
- src/pages/index.tsx
- src/pages/question.tsx
- src/pages/result.tsx
> style: 디자인 검수 반영

- src/pages/begin.tsx
- src/pages/index.tsx
- src/pages/result.tsx
> 질문 페이지 devision bar 너비 수정

- src/pages/browsing.tsx
- src/pages/index.tsx
> fix: 디자인 검수 누락 적용

- src/components/common/Button.tsx
- src/components/common/Top20List.tsx
- src/pages/_app.tsx
- src/pages/begin.tsx
- src/pages/browsing.tsx
- src/pages/question.tsx
- src/pages/result.tsx
- src/styles/globals.css
-디자인 검수
-버튼 리팩토링
-카톡인앱일떄만 크롬으로 이동
-질문 페이지 리팩토링
> style,refactor: 디자인 검수 코드 리팩토링

- src/components/common/Button.tsx
- src/components/common/layout.tsx
- src/pages/result.tsx
- src/styles/globals.css
> fix: 디자인 반영

- src/components/common/Button.tsx
- src/components/result/Card.tsx
- src/components/result/FitHobby.tsx
- src/components/result/Model.tsx
- src/pages/begin.tsx
- src/pages/browsing.tsx
- src/pages/result.tsx
- 유저명 입력페이지 - 버튼과 유저명 입력하는 창 사이 간격 일정하게
- 스크롤 - 스크롤를 확내리면 맨밑까지 안내려가거나, 확위로 올릴때 안올라가거나
- 결과페이지 스크롤 추가
- Minified React Error에 관한 글 참고해서 수정해주세요.
- 결과페이지 계속 위로 스크롤되는 버그  픽스
> fix,refactor: 최종 2차 QA 리팩토링

- robots.txt
- src/components/MetaHead.tsx
- src/pages/_app.tsx
- SEO설정
- 카카오톡 인앱 링크 수정
- GA코드 추가
- 콘솔 에러 숨기기
> 프로젝트 3차 QA 리팩토링

- src/components/MetaHead.tsx
- src/components/common/GoogleAd.tsx
- src/components/result/Share.tsx
- src/pages/index.tsx
- src/pages/question.tsx
- src/pages/result.tsx
구글 광고 추가했습니다
에러도 안 나고,
컴포넌트(<GoogleAd>)로 만들어놔서 쓰기 편할겁니다.
> [Feat] Add google ad

- src/components/common/GoogleAd.tsx
> fix:구글 애즈 반영

- src/components/result/HobbyDetail.tsx
> 상세페이지 배경 색 변경

- src/components/common/Button.tsx
- src/components/result/Card.tsx
- src/pages/result.tsx
> 디자인 피그마와 다른 부분 수정

- src/components/MetaHead.tsx
- src/components/common/Button.tsx
- src/components/common/GoogleAd.tsx
- src/components/common/ResultLoader.tsx
- src/components/common/Top20List.tsx
- src/components/result/Card.tsx
- src/components/result/FitHobby.tsx
- src/components/result/HobbyDetail.tsx
- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/result.tsx
> fix: 구글 애즈 반영
